### ISSUE TITLE
Finding the duplicate strings should be determined across the current scope

### ISSUE THREAD

**Issue by hzoo** [hzoo/babel-plugin-dedupe-string-literals#2]
Basically need to account for `[['longstring', 'longstring'], ['longstring', 'longstring']]`, since currently it only dedupes per array.

https://github.com/hzoo/babel-plugin-dedupe-string-literals/blob/master/test/fixtures/example/expected.js as an example

cc @mathiasbynens - I think that's a blocker for the files you mentioned since I saw the nested arrays.

**Comment by mathiasbynens** [comment]
Correct, the file format changed recently because I switched to Maps. Here’s an example: https://github.com/mathiasbynens/unicode-8.0.0/blob/233fdfc0cd3173bef5bce39b00ebaee534592ae6/bidi-brackets/index.js

**Comment by hzoo** [comment]
Ok this wasn't that bad actually - fixed in https://github.com/hzoo/babel-plugin-dedupe-string-literals/commit/8a83ce805a6bb12f89c9283cba747882644a0586.

Literally just moved the cache to a per program/file level (not at the transform level since then it would be applied across all files), and then saved a reference to the first string.
